apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pometheus-app
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s 
    port: web
  selector:
    matchLabels:
      app: gitlab-api